src/core/views.py
from flask import Blueprint, render_template

core_bp = Blueprint('core', __name__,
                    template_folder='templates',
                    static_folder='static',
                    )


@core_bp.route('/')
def home():
    title = 'Главная - МВ проект \'Scripts DataBase\' - Камила Титова'
    return render_template('core/index.html', title=title)

src/scripts/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user

from src import db
from src.scripts.models import Script

from src.scripts.forms import AddScriptForm
from src.users.models import User

scripts_bp = Blueprint("scripts", __name__,
                       template_folder="templates",
                       static_folder="static",
                       url_prefix="/scripts")


@scripts_bp.route("/")
@login_required
def scripts_list():
    title = "Список SQL скриптов - МВ проект 'Scripts DataBase' - Камила Титова"
    if current_user.is_authenticated:
        if current_user.allow_see_others:
            scripts = Script.query.all()
        else:
            scripts = Script.query.filter_by(user_id=current_user.id).all()
        return render_template('scripts/scripts_list.html', title=title, scripts=scripts)
    flash("You are not authenticated. Please login.", "danger")
    return render_template("core/index.html")


@scripts_bp.route("/add", methods=["GET", "POST"])
@login_required
def add_script():
    form = AddScriptForm(request.form)
    form.user_id.choices = []
    users = User.query.all()
    form.user_id.choices = [user.email for user in users]
    if form.validate_on_submit():
        script = Script(name=form.name.data, description=form.description.data, code=str(form.code.data),
                        user_id=form.user_id.data)
        db.session.add(script)
        db.session.commit()
        flash(f"SQL script {form.name.data} was successfully added to DB", "success")
        return redirect(url_for("scripts.scripts_list"))
    return render_template("scripts/add_script.html", users=users, form=form)

src/users/views.py
from datetime import datetime

from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, login_required, logout_user

from src import db, bcrypt
from src.users.models import User

from .forms import LoginForm, RegisterForm

users_bp = Blueprint('users', __name__,
                     template_folder='templates',
                     static_folder='static',
                     url_prefix='/users')


@users_bp.route('/')
def users_list():
    title = 'Список пользователей - МВ проект \'Scripts DataBase\' - Камила Титова'
    if current_user.is_authenticated:
        if current_user.is_admin:
            users = User.query.all()
            return render_template('users/users_list.html', title=title, users=users)
        else:
            flash("You do not have permission to view this page.", "danger")
    return render_template('core/index.html', title=title)


@users_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        if not current_user.is_admin:
            flash("You are already registered.", "info")
            return redirect(url_for("core.home"))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(name=form.name.data, email=form.email.data, password=form.password.data,
                    mv_user_id=form.mv_user_id.data)
        db.session.add(user)
        db.session.commit()
        if not user.is_admin:
            login_user(user)
            flash("You registered and are now logged in. Welcome!", "success")
            return redirect(url_for("core.home"))
        else:
            flash(f"User {user.email} successfully registered!", "success")
    return render_template("users/register.html", form=form)


@users_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("core.home"))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            current_user.last_login_on = datetime.now()
            db.session.commit()
            return redirect(url_for("core.home"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("users/login.html", form=form)
    return render_template("users/login.html", form=form)


@users_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("users.login"))

templates/base.html
<!DOCTYPE html>
<html lang="ru" class="h-100">
<head>
    {% block title %}
        {% if title %}
            <title>{{title}}</title>
        {% else %}
            <title>МВ проект \'Scripts DataBase\' - Камила Титова (@kamilla_ti)</title>
        {% endif %}
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}
    {% endblock %}
    <link rel="icon" type="image/x-icon"
          href="https://assets-cdn.mvideo.ru/ef6f56ef720e358a53c59743c3d15bd80a93896f/favicon.ico">
    <link rel="preload stylesheet" type="text/css" crossorigin="anonymous" as="style"
          href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="preload stylesheet" type="text/css" as="style"
          href="{{ url_for('static', filename='css/styles.css') }}">
    {% block css %}{% endblock %}
</head>
<body class="d-flex flex-column h-100">
{% block header %}
    {% include 'header.html' %}
{% endblock %}
<!-- messages -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="row pt-3">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-4"></div>
        </div>
    {% endif %}
{% endwith %}
{% block content %}
{% endblock %}
{% block footer %}
    {% include 'footer.html' %}
{% endblock %}
<!-- Bootstrap core JS-->
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>
</html>

templates/footer.html
{% block footer %}
    <footer class="footer mt-auto py-3 bg-body-tertiary">
        <div class="container-fluid">
            <div class="ps-5 pe-1">
                &copy;
                <script>document.write(new Date().getFullYear())</script>
                MVideo - SQL Script Database by Kamila Titova.
            </div>
        </div>
    </footer>
{% endblock %}

templates/header.html
{% block header %}
    <nav class="navbar navbar-expand-sm bg-body-tertiary" aria-label="Third navbar example">
        <div class="container-fluid">
            <a class="navbar-brand" href="https://www.mvideo.ru/">
                <img loading="lazy" alt="https://www.mvideo.ru/" width="117" height="48"
                     src="https://cms.mvideo.ru/magnoliaPublic/dam/jcr:a036485b-d677-429c-9886-1ab6b62e31fd">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03"
                    aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExample03">
                <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                    <li class="nav-item">
                        <a class="nav-link greeting" aria-current="page" href="{{ url_for('core.home') }}">Главная</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle greeting" href="{{ url_for('scripts.scripts_list') }}"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            SQL скрипты
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item greeting" href="{{ url_for('scripts.add_script') }}">
                                    Добавить SQL скрипт вручную
                                </a>
                            </li>
                            <li><a class="dropdown-item greeting" href="#">Загрузить SQL скрипт из папки</a></li>
                            <li>
                                <a class="dropdown-item greeting" href="{{ url_for('scripts.scripts_list') }}">
                                    Список SQL скриптов
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle greeting" href="{{ url_for('users.users_list') }}"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Пользователи
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item greeting" href="{{ url_for('users.register') }}">
                                    Регистрация нового пользователя
                                </a>
                            </li>
                            {% if not current_user.is_authenticated %}
                                <li>
                                    <a class="dropdown-item greeting" href="{{ url_for('users.login') }}">
                                        Авторизация
                                    </a>
                                </li>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                                <li>
                                    <a class="dropdown-item greeting" href="{{ url_for('users.users_list') }}">
                                        Список пользователей (адм.)
                                    </a>
                                </li>
                                <li><a class="dropdown-item greeting" href="#">Мои скрипты</a></li>
                                <li>
                                    <a class="dropdown-item greeting" href="{{ url_for('users.logout') }}">Выйти</a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
                <form role="search">
                    <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                </form>
            </div>
        </div>
    </nav>
{% endblock %}